# 예러 처리

컴파일 오류: 코드가 잘못되었음을 알려줌(문법적 오류/에러)      
런타임 오류: 여러가지 다양한 이유로 앱이 실행되는 동안 발생 -> 앱이 꺼진다.     
* 그래서 미리 발생가능한 에러를 파악 후 올바르게 처리하면 앱의 꺼짐을 막을 수 있다.

앱이 실행하는 중간에 왜 꺼질까?
- 어떤 애기치 못한 상황이 발생할 수 있다.
- (네트워크 통신을 하는 등의 경우에서) 서버에서 데이터를 못 받아와서 ===> 꺼짐

만약에 앱이 종료되면서 -> "서버에서 문제가 발생했습니다." 잠시뒤에 다시 접속해주세요"리고 알려주는 것이 좋은가? 
 - 프로세스 중에서, 예외적인 상황(에러)이 발생하는 것이 미리 가능성 등을 처리해 놓으면
   앱이 무작정 꺼지는 것을 예방할 수 있음 ⭐️

⭐️에러는 일반적으로 동작. 즉, 함수의 처리과정에서 일어남 ⭐️  
   

### (에러를 던지는 함수)와 처리
> 에러 처리와 과정 (3단계)

1. 에러의 정의
2. 에러가 발생할 수 잇는 함수에 대한 정의
3. 에러가 발생할 수 있는 함수의 처리(함수의 실행) ===> 기존과 조금다르다 (`try`와 `do-catch`문으로 처리)
   - `do블럭`  - 함수를 통한 정상적인 처리의 경우 실행하는 블럭
   - `catch블럭` - 함수가 에러를 던졌을 경우의 처리 실행하는 블럭    

```swift
enum HeightError: Error { // 에러 프로토콜 채택
  case maxHeight
  case minHeight

}

func checkingHeight(height: Int) throws -> Bool {    // (에러를 던잘수 있는 함수 타입이다)
    
    if height > 190 {
        throw HeightError.maxHeight
    } else if height < 130 {
        throw HeightError.minHeight
    } else {
        if height >= 160 {
            return true
        } else {
            return false
        }
    }
}



do {
    
    let isChecked = try checkingHeight(height: 30)
    if isChecked {
        print("참")
    }else {
        print("거짓")
    }
    print("놀이기구 타는 것 가능: \(isChecked)")
    
} catch {
    //에러가 발생한경우 처리
    print("놀이기구 타는 것 불가능 ")
    
}
```

### 에러 처리 방법
* 에러 함수 정의
* 에러를 처리하는 방법(try/ try? / try!)

1. 에러 정식 처리 방법
```swift
do {
  let isChecked = try checkingHeight(height: 30)
  if isChecked {
    print("청룡열차 가능")
  }else {
    print("후룸 라이드 가능")
  }
} catch {
  print("놀이기구 타는 것 불가능")
}
```    
2. try?(옵셔널 트라이) ===> `옵셔널 타입`으로 리턴
    * 정상적인 경우 ===> (정상)리턴타입으로 리턴   
    * 에러가 발생하면 ===> nil리턴  
```swift
let isChecked = try? checkingHeight(height: 200)      // Bool?

if let isChecked = isChecked {
    print(isChecked)
}
// 당연히, 옵셔널 타입을 벗겨서 사용해야함
```
3. try! (Forced 트라이) ===> `에러가 날 수 없는 경우에`만 사용 가능
   * 정상적인 경우 ==> (정상)리턴타입으로 리턴
   * 에러가 발생하면 ==> 런타임에러        
```swift

let isChecked2: Bool = try! checkingHeight(height: 150)      // Bool
// 에러가 발생할 수 없다고 확신이 있는 경우만 사용해야 함

```
